import type { SeoCapabilityId, SeoCapabilityV1 } from "@cie/contracts";
import type { SortDirection } from "@cie/contracts";

/**
 * The SEO capability catalog ("the menu"). Metadata only — fulfillment logic
 * lives in SEOOS. Capabilities that only summarize already-synced data are
 * cacheable/auto-fulfillable; anything that starts a paid scan, writes
 * externally, or creates work requires approval.
 */
export const SEO_CAPABILITY_CATALOG: SeoCapabilityV1[] = [
  {
    schemaVersion: 1,
    id: "full-monthly-package",
    version: 1,
    label: "Full Monthly SEO Package",
    description:
      "The complete monthly rollup: rankings, grids, market share, GBP, reviews, work completed, risks, and next-30-day plan.",
    requiredInputs: ["reportingPeriod"],
    supportedWindows: ["last_30d", "last_60d", "last_90d", "custom"],
    supportedFilters: { keywords: true, locations: true, gbpProfiles: true, competitors: true },
    dataSources: ["rank-tracker", "geogrid", "google-business-profile", "google-search-console", "map-checkins", "clickup"],
    cacheable: true,
    requiresNewScan: false,
    canCauseCost: false,
    canCauseSideEffect: false,
    requiredPermission: "seo.package.read",
    requiredApproval: false,
    availability: "Assembled from the latest synced snapshots",
  },
  {
    schemaVersion: 1,
    id: "executive-seo-summary",
    version: 1,
    label: "Executive SEO Summary",
    description: "A short, account-manager-ready summary of the period's SEO story.",
    requiredInputs: ["reportingPeriod"],
    supportedWindows: ["last_30d", "last_90d", "custom"],
    supportedFilters: { keywords: false, locations: true, gbpProfiles: false, competitors: false },
    dataSources: ["rank-tracker", "geogrid", "google-business-profile"],
    cacheable: true,
    requiresNewScan: false,
    canCauseCost: false,
    canCauseSideEffect: false,
    requiredPermission: "seo.package.read",
    requiredApproval: false,
    availability: "Assembled from the latest synced snapshots",
  },
  {
    schemaVersion: 1,
    id: "keyword-ranking-summary",
    version: 1,
    label: "Keyword Ranking Summary",
    description: "Average position, top-3/10 coverage, movement, and distribution for tracked keywords.",
    requiredInputs: ["reportingPeriod"],
    supportedWindows: ["last_7d", "last_30d", "last_90d", "custom"],
    supportedFilters: { keywords: true, locations: true, gbpProfiles: false, competitors: false },
    dataSources: ["rank-tracker"],
    cacheable: true,
    requiresNewScan: false,
    canCauseCost: false,
    canCauseSideEffect: false,
    requiredPermission: "seo.package.read",
    requiredApproval: false,
    availability: "From the latest Rank Tracker sync",
  },
  {
    schemaVersion: 1,
    id: "keyword-deep-dive",
    version: 1,
    label: "Keyword Deep Dive",
    description: "Detailed per-keyword history, target URLs, intent, and opportunity analysis.",
    requiredInputs: ["reportingPeriod", "keywordIds"],
    supportedWindows: ["last_30d", "last_90d", "custom"],
    supportedFilters: { keywords: true, locations: true, gbpProfiles: false, competitors: true },
    dataSources: ["rank-tracker", "google-search-console"],
    cacheable: true,
    requiresNewScan: false,
    canCauseCost: false,
    canCauseSideEffect: false,
    requiredPermission: "seo.package.read",
    requiredApproval: false,
    availability: "From synced ranking + Search Console data",
  },
  {
    schemaVersion: 1,
    id: "grid-heatmap-analysis",
    version: 1,
    label: "Grid / Heatmap Analysis",
    description: "Local grid coverage, average grid rank, and heatmap comparison over time.",
    requiredInputs: ["reportingPeriod", "locationIds"],
    supportedWindows: ["last_30d", "last_90d", "custom"],
    supportedFilters: { keywords: true, locations: true, gbpProfiles: true, competitors: true },
    dataSources: ["geogrid"],
    cacheable: true,
    requiresNewScan: false,
    canCauseCost: false,
    canCauseSideEffect: false,
    requiredPermission: "seo.package.read",
    requiredApproval: false,
    availability: "From the latest completed grid scans",
  },
  {
    schemaVersion: 1,
    id: "market-share-analysis",
    version: 1,
    label: "Market Share / Share of Local Voice",
    description: "Share of local voice vs. tracked competitors across the grid.",
    requiredInputs: ["reportingPeriod", "locationIds"],
    supportedWindows: ["last_30d", "last_90d", "custom"],
    supportedFilters: { keywords: true, locations: true, gbpProfiles: false, competitors: true },
    dataSources: ["geogrid", "rank-tracker"],
    cacheable: true,
    requiresNewScan: false,
    canCauseCost: false,
    canCauseSideEffect: false,
    requiredPermission: "seo.package.read",
    requiredApproval: false,
    availability: "Derived from grid + ranking snapshots",
  },
  {
    schemaVersion: 1,
    id: "gbp-performance",
    version: 1,
    label: "GBP Performance",
    description: "Google Business Profile calls, direction requests, views, and interactions.",
    requiredInputs: ["reportingPeriod", "gbpProfileIds"],
    supportedWindows: ["last_30d", "last_90d", "custom"],
    supportedFilters: { keywords: false, locations: true, gbpProfiles: true, competitors: false },
    dataSources: ["google-business-profile"],
    cacheable: true,
    requiresNewScan: false,
    canCauseCost: false,
    canCauseSideEffect: false,
    requiredPermission: "seo.package.read",
    requiredApproval: false,
    availability: "From the latest GBP sync",
  },
  {
    schemaVersion: 1,
    id: "map-checkin-activity",
    version: 1,
    label: "Map Check-In Activity",
    description: "Map check-in counts, coverage, and team activity for the period.",
    requiredInputs: ["reportingPeriod"],
    supportedWindows: ["last_30d", "last_90d", "custom"],
    supportedFilters: { keywords: false, locations: true, gbpProfiles: true, competitors: false },
    dataSources: ["map-checkins"],
    cacheable: true,
    requiresNewScan: false,
    canCauseCost: false,
    canCauseSideEffect: false,
    requiredPermission: "seo.package.read",
    requiredApproval: false,
    availability: "From the shared Map Check-Ins connection",
  },
  {
    schemaVersion: 1,
    id: "review-management-summary",
    version: 1,
    label: "Review Management Summary",
    description: "Reviews received/answered, response SLA, and reputation signals where a source supports it.",
    requiredInputs: ["reportingPeriod"],
    supportedWindows: ["last_30d", "last_90d", "custom"],
    supportedFilters: { keywords: false, locations: true, gbpProfiles: true, competitors: true },
    dataSources: ["google-business-profile"],
    cacheable: true,
    requiresNewScan: false,
    canCauseCost: false,
    canCauseSideEffect: false,
    requiredPermission: "seo.package.read",
    requiredApproval: false,
    availability: "From connected review sources",
  },
  {
    schemaVersion: 1,
    id: "competitor-analysis",
    version: 1,
    label: "Competitor Analysis",
    description: "Keyword/grid overlap, market share, and observed strengths vs. confirmed competitors.",
    requiredInputs: ["reportingPeriod", "competitorIds"],
    supportedWindows: ["last_30d", "last_90d", "custom"],
    supportedFilters: { keywords: true, locations: true, gbpProfiles: false, competitors: true },
    dataSources: ["geogrid", "rank-tracker"],
    cacheable: true,
    requiresNewScan: false,
    canCauseCost: false,
    canCauseSideEffect: false,
    requiredPermission: "seo.package.read",
    requiredApproval: false,
    availability: "From synced competitor/grid data",
  },
  {
    schemaVersion: 1,
    id: "work-completed",
    version: 1,
    label: "Work Completed",
    description: "SEO work orders and deliverables completed in the period.",
    requiredInputs: ["reportingPeriod"],
    supportedWindows: ["last_30d", "last_90d", "custom"],
    supportedFilters: { keywords: false, locations: false, gbpProfiles: false, competitors: false },
    dataSources: ["internal-database", "clickup"],
    cacheable: true,
    requiresNewScan: false,
    canCauseCost: false,
    canCauseSideEffect: false,
    requiredPermission: "seo.package.read",
    requiredApproval: false,
    availability: "From work-order records",
  },
  {
    schemaVersion: 1,
    id: "deliverables-status",
    version: 1,
    label: "Deliverables Status",
    description: "Open, in-progress, and delivered items with owners and due dates.",
    requiredInputs: [],
    supportedWindows: ["last_30d", "custom"],
    supportedFilters: { keywords: false, locations: false, gbpProfiles: false, competitors: false },
    dataSources: ["internal-database", "clickup"],
    cacheable: true,
    requiresNewScan: false,
    canCauseCost: false,
    canCauseSideEffect: false,
    requiredPermission: "seo.package.read",
    requiredApproval: false,
    availability: "From work-order records",
  },
  {
    schemaVersion: 1,
    id: "category-service-change-explanation",
    version: 1,
    label: "Category / Service Change Explanation",
    description: "Client-safe rationale for a proposed primary-category, service, or key-page change.",
    requiredInputs: ["gbpProfileIds"],
    supportedWindows: ["custom"],
    supportedFilters: { keywords: true, locations: true, gbpProfiles: true, competitors: true },
    dataSources: ["geogrid", "google-business-profile", "rank-tracker"],
    cacheable: true,
    requiresNewScan: false,
    canCauseCost: false,
    canCauseSideEffect: false,
    requiredPermission: "seo.package.read",
    requiredApproval: true,
    availability: "Generated from evidence; requires review",
  },
  {
    schemaVersion: 1,
    id: "website-technical-audit",
    version: 1,
    label: "Website Technical Audit",
    description: "Crawl-based technical SEO findings. Staged pending audit-source licensing/feasibility.",
    requiredInputs: ["websiteUrl"],
    supportedWindows: ["custom"],
    supportedFilters: { keywords: false, locations: false, gbpProfiles: false, competitors: false },
    dataSources: ["internal-database"],
    cacheable: false,
    requiresNewScan: true,
    canCauseCost: true,
    canCauseSideEffect: false,
    requiredPermission: "seo.request.fulfill",
    requiredApproval: true,
    availability: "Requires a crawl/audit source (staged)",
  },
  {
    schemaVersion: 1,
    id: "risks-and-blockers",
    version: 1,
    label: "Risks & Blockers",
    description: "Current risks, data gaps, and blockers affecting SEO outcomes.",
    requiredInputs: [],
    supportedWindows: ["last_30d", "custom"],
    supportedFilters: { keywords: false, locations: false, gbpProfiles: false, competitors: false },
    dataSources: ["internal-database"],
    cacheable: true,
    requiresNewScan: false,
    canCauseCost: false,
    canCauseSideEffect: false,
    requiredPermission: "seo.package.read",
    requiredApproval: false,
    availability: "From project + data-health records",
  },
  {
    schemaVersion: 1,
    id: "next-30-day-recommendations",
    version: 1,
    label: "Next 30-Day Recommendations",
    description: "Evidence-grounded prioritized recommendations for the coming period.",
    requiredInputs: ["reportingPeriod"],
    supportedWindows: ["last_30d", "last_90d"],
    supportedFilters: { keywords: true, locations: true, gbpProfiles: true, competitors: true },
    dataSources: ["rank-tracker", "geogrid", "google-business-profile", "internal-database"],
    cacheable: true,
    requiresNewScan: false,
    canCauseCost: false,
    canCauseSideEffect: false,
    requiredPermission: "seo.package.read",
    requiredApproval: false,
    availability: "Generated from synced evidence",
  },
  {
    schemaVersion: 1,
    id: "custom-question",
    version: 1,
    label: "Custom Question",
    description: "A free-form question answered from available SEO evidence.",
    requiredInputs: ["instructions"],
    supportedWindows: ["last_30d", "last_90d", "custom"],
    supportedFilters: { keywords: true, locations: true, gbpProfiles: true, competitors: true },
    dataSources: ["internal-database"],
    cacheable: true,
    requiresNewScan: false,
    canCauseCost: false,
    canCauseSideEffect: false,
    requiredPermission: "seo.package.read",
    requiredApproval: false,
    availability: "Answered from available evidence",
  },
];

const BY_ID = new Map<SeoCapabilityId, SeoCapabilityV1>(
  SEO_CAPABILITY_CATALOG.map((c) => [c.id, c]),
);

export function getCapability(id: SeoCapabilityId): SeoCapabilityV1 | undefined {
  return BY_ID.get(id);
}

/** Map the user-facing lead/call sort alias to the canonical direction. */
export function sortDirectionFromAlias(alias: "asc" | "desc"): SortDirection {
  return alias === "asc" ? "oldest_first" : "newest_first";
}

export function sortDirectionToAlias(direction: SortDirection): "asc" | "desc" {
  return direction === "oldest_first" ? "asc" : "desc";
}
